### ISSUE TITLE
Introduce metapackage history pages

### ISSUE THREAD

**Issue by AMDmi3** [repology/repology#535]
Metapackage history is almost ready to use, some prerequisites left before enabling it for production use:

- [x] absolute times for history entries (#534)
- [x] tracking times between version updates
- [x] at least a week of testing and data gathering
- [x] history end events (#540, requires #543)
- [x] improve handling of pseudo-updates (such as 1.0 version appearing in addition to 1.0.0) (#577)
- [x] separate handling of devel and newest versions
- [x] #411 should be implemented first too to prevent polluting history with 'blinking' packages
- [ ] ~~decide what to do with metapackage renames~~ (I don't think we can/need to deal with this now)
- [x] add a more elaborate comment on possible discrepancies between history and real project release timeline 
- [x] fedora package blinks (#579)
- [ ] investigate massive derelease events (versions going backwards?)

**Comment by AMDmi3** [comment]
Well I guess I'm finally satistfied in how it works. The last issue is still there, but it's being tracked.
